### ISSUE TITLE
 failure of _debugStream->

### ISSUE THREAD

**Issue by neilh10** [EnviroDIY/SensorModbusMaster#11]
I'm having an issue with a KellerParent request dying.
It works if the MS_KELLERPARENT_DEBUG_DEEP is enabled.
This used to work for me with AVR, but now using it with ARM/SAMD so investigating why its different now.

KellerParent.cpp
On MS_KELLERPARENT_DEBUG_DEEP
    #ifdef MS_KELLERPARENT_DEBUG_DEEP
        sensor.setDebugStream(&DEEP_DEBUGGING_SERIAL_OUTPUT);

It sets up the output for  SensorModbusMaster_ID1824\src\SensorModbusMaster.cpp "0.6.5"
_debugStream->print("Raw Request >>> ");
which results in SensorModbusMaster_ID1824\src\SensorModbusMaster.h
    void setDebugStream(Stream *stream){_debugStream = stream;}

however the standard case with no MS_KELLERPARENT_DEBUG_DEEP has _debugStream uninitialized  - which is likely to be 0's or NULL
    Stream *_debugStream;  // The stream instance (serial port) for debugging
which would cause a FAILURE  when executing
     NULL->print("Raw Request >>> ");

I think the solution is to put a check in 
For SensorModbusMaster.h   _debugStream rename to _debugStream1
in SensorModbusMaster.cpp
#define _debugStream  if (_debugStream1 != NULL) _debugStream1->print("Raw Request >>> ");

So checking in if anybody else has seen this and/or any other solution.

**Comment by SRGDamia1** [comment]
Thank you for this!  I think this might be one of those goofy AVR-serial-initialization things.  Anyway, I'm happy with your fix.  Thank you!
