### ISSUE TITLE
Lightening protection suggestion

### ISSUE THREAD

**Issue by neilh10** [EnviroDIY/SensorModbusMaster#15]
The RS485 hybrid has some defined lightening or ESD clamping components. 
There has been some discussion of this elsewhere. 
However, my analysis, is that the clamping components need a  a low impedance path to ground.
I've added a thick grounding wire to the hybrids ground connection, that can then be connected to an external earth connection. I'm using solid core that I have to hand 18 AWG, or 1mm dia. Ideally it should be green. I'm making the tail 12" long, and it can be trimmed on installation if necessary.

![RS485hybridBuiltA (Large)](https://user-images.githubusercontent.com/2766619/91079027-5c374e80-e5f8-11ea-8dcd-3816c8a940a4.jpg)

Background: As an EE, I've seen a number of boards that have conducted lightening currents - been hit by lightening.  The number one rule is that shouldn't burst in to flames, potentially causing further damage.
While grounding circuits are not guaranteed to conduct all large currents to ground, having a low ohmic resistance to ground is a starting point. 
For areas that have a large number of lightening strikes, local knowledge and code usually defines how a good electrical ground is formed. 
There is an IEEE specification on grounding but I haven't got a direct reference on it.
Living in California, while lightening isn't common, we've just been through a storm that was estimated to have created 12,000 strikes, which then caused some 600fires.
The state with the most lightening strikes is supposed to be Florida. However the subsoil is largely on a reef, and I've been to technical presentations that say Florida is the most difficult to form a good ground.

**Comment by aufdenkampe** [comment]
This issue has been functionally moved to the https://github.com/EnviroDIY/Mayfly-Modbus-Wing repo. See:
- https://github.com/EnviroDIY/Mayfly-Modbus-Wing/issues/1

If this issue needs further discussion, please continue it in a new issue in https://github.com/EnviroDIY/Mayfly-Modbus-Win
